### ISSUE TITLE
Arguments order in add_video function in lib/membrane/implementations/opengl/rust.ex changes order needlessly.

### ISSUE THREAD

**Issue by WojciechBarczynski** [membraneframework-labs/membrane_video_compositor_plugin#36]
Arguments order in `add_video` function in `lib/membrane/implementations/opengl/rust.ex` changes order needlessly, which is confusing. I think it should be changed. We would need to change order in `test/opengl/opengl_rust_native_test.exs` as well.

**Comment by jerzywilczek** [comment]
+1, state should be passed as the first argument everywhere

**Comment by Janix4000** [comment]
See #38

**Comment by WojciechBarczynski** [comment]
Fixed with #38 merge.
